version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=hospitalAppointmentScheduler
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=hospitalAppointmentScheduler
    volumes:
      - mysql_data:/var/lib/mysql
      - ./01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./02-init.sql:/docker-entrypoint-initdb.d/02-init.sql

volumes:
  mysql_data:
